package com.delex.ffsensiboost.data.model

/**
 * Data model representing device specifications extracted from Android system.
 * This is Factor A of the Sensitivity Generation Algorithm.
 */
data class DeviceSpecifications(
    val deviceModel: String,
    val deviceManufacturer: String,
    val androidVersion: Int,
    val apiLevel: Int,
    val totalRAM: Long,
    val availableRAM: Long,
    val processorCores: Int,
    val screenResolutionWidth: Int,
    val screenResolutionHeight: Int,
    val screenRefreshRate: Float,
    val deviceEraYear: Int,
    val isDPICustomizable: Boolean,
    val screenDensity: Float,
    val screenDensityDPI: Int
) {
    /**
     * Calculate device performance rating (0-100)
     * Higher = Better device
     */
    fun getPerformanceRating(): Float {
        var rating = 0f
        
        // RAM contribution (0-30)
        val ramRating = when {
            totalRAM >= 12_000_000_000L -> 30f  // 12GB+
            totalRAM >= 8_000_000_000L -> 25f   // 8GB+
            totalRAM >= 6_000_000_000L -> 20f   // 6GB+
            totalRAM >= 4_000_000_000L -> 15f   // 4GB+
            else -> 10f
        }
        
        // CPU contribution (0-30)
        val cpuRating = when {
            processorCores >= 8 -> 30f
            processorCores >= 6 -> 25f
            processorCores >= 4 -> 20f
            else -> 10f
        }
        
        // API Level contribution (0-20)
        val apiRating = when {
            apiLevel >= 33 -> 20f
            apiLevel >= 31 -> 18f
            apiLevel >= 29 -> 15f
            apiLevel >= 26 -> 10f
            else -> 5f
        }
        
        // Screen refresh rate contribution (0-20)
        val refreshRating = when {
            screenRefreshRate >= 120 -> 20f
            screenRefreshRate >= 90 -> 18f
            screenRefreshRate >= 60 -> 15f
            else -> 10f
        }
        
        rating = ramRating + cpuRating + apiRating + refreshRating
        return rating.coerceIn(0f, 100f)
    }
}

/**
 * Data model for swipe test results.
 * This is Factor B of the Sensitivity Generation Algorithm.
 */
data class SwipeTestResult(
    val roundSpeeds: List<Float>,  // pixels per millisecond for each round
    val averageSpeed: Float,
    val consistencyScore: Float,    // 0-100: how consistent were the swipes
    val peakSpeed: Float,
    val testDuration: Long          // milliseconds
) {
    /**
     * Calculate normalized swipe factor (0-100)
     * Higher speed = lower factor needed
     */
    fun getNormalizedSwipeFactor(): Float {
        // Base on average speed with consistency weighting
        val speedFactor = (averageSpeed / 2.0f) * 100f  // Normalize assuming max ~2.0 px/ms
        val consistency = consistencyScore / 100f
        
        return (speedFactor * consistency).coerceIn(20f, 100f)
    }
}

/**
 * Final Sensitivity Configuration generated by the algorithm.
 * Contains all Free Fire sensitivity settings optimized for the user.
 */
data class SensitivityConfiguration(
    val generalSensitivity: Int,      // 1-200
    val redDotSensitivity: Int,       // 1-200
    val scope2xSensitivity: Int,      // 1-200
    val scope4xSensitivity: Int,      // 1-200
    val sniperScopeSensitivity: Int,  // 1-200
    val freeLookSensitivity: Int,     // 1-200
    val fireButtonSize: Int,          // 50-150% (percentage)
    val recommendedDPI: Int,          // Custom DPI value
    val algorithmVersion: Int = 1,
    val deviceRating: Float,
    val swipeFactor: Float,
    val timestamp: Long = System.currentTimeMillis(),
    val isOptimized: Boolean = true
) {
    /**
     * Export settings as string for easy sharing
     */
    fun exportAsString(): String {
        return """
            ═════ FF SENSI BOOST CONFIGURATION ═════
            
            📱 AIMING SETTINGS
            ├─ General: $generalSensitivity
            ├─ Red Dot: $redDotSensitivity
            ├─ 2x Scope: $scope2xSensitivity
            ├─ 4x Scope: $scope4xSensitivity
            ├─ Sniper: $sniperScopeSensitivity
            └─ Free Look: $freeLookSensitivity
            
            🎮 GAMEPLAY SETTINGS
            ├─ Fire Button Size: $fireButtonSize%
            └─ Android DPI: $recommendedDPI
            
            ⚡ OPTIMIZATION METRICS
            ├─ Device Rating: ${String.format("%.1f", deviceRating)}/100
            ├─ Swipe Factor: ${String.format("%.1f", swipeFactor)}/100
            └─ Algorithm: v$algorithmVersion
            
            Generated: ${java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(java.util.Date(timestamp))}
            ════════════════════════════════════
        """.trimIndent()
    }
}

/**
 * System Booster Statistics
 */
data class BoosterStats(
    val cacheSize: Long,
    val trashSize: Long,
    val temporaryFiles: Long,
    val backgroundProcesses: Int,
    val totalOptimizationSize: Long,
    val timestamp: Long = System.currentTimeMillis()
) {
    fun getCacheSizeInMB(): Float = cacheSize / (1024 * 1024).toFloat()
    fun getTrashSizeInMB(): Float = trashSize / (1024 * 1024).toFloat()
    fun getTempSizeInMB(): Float = temporaryFiles / (1024 * 1024).toFloat()
    fun getTotalOptimizationSizeInMB(): Float = totalOptimizationSize / (1024 * 1024).toFloat()
}
