name: Build Free Fire App
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: List files to find Gradle
        run: |
          echo "Looking for gradlew..."
          find . -name "gradlew"
          echo "--- List of files in the project ---"
          ls -R
